server:
  port: 9100

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: b2b3c55a-abe5-47a4-a47e-03c57138d1d7
#        group: dev
#    gateway:
#      discovery:
#        locator:
#          enabled: true  # switch auto route
#      routes:
#        - id: http
#          uri: http://httpbin.org
#          predicates:
#            - Path=/httpbin/**
#          filters:
#            - StripPrefix=1

#        - id: nacos
#          uri: lb://nacos-payment-provider
#          predicates:
#            - Path=/payment-service/**
#          filters:
#            - AddResponseHeader=Hello, Gateway
#            - AddResponseHeader=Hi, Java
#            - StripPrefix=1
#            - Authorize=true